### ISSUE TITLE
Mortalens and Zenox can't research specialised destroyers or specialised cruisers.

### ISSUE THREAD

**Issue by LizDragoness** [lucky-wolf/DW2-XL#4]
The techs require enhanced sensors and advanced sensors, which neither race can research.
![image](https://user-images.githubusercontent.com/123353916/213981856-a72bb09c-dfbd-40e3-a3c2-fd26c3840c7a.png)

**Comment by lucky-wolf** [comment]
Sorry - which races are you referring to?

**Comment by LizDragoness** [comment]
Having started a game as the Mortalens in tech three, I cannot research specialised destroyers with the racial sensor tech unlocked, because it has no requirement at all for Multi-Tracking Sensors, only Enhanced Sensors. ![image](https://user-images.githubusercontent.com/123353916/215812781-49525777-bc1b-4add-82a8-1649d1bfa045.png)
![image](https://user-images.githubusercontent.com/123353916/215813483-697f76a5-2c48-438f-9601-5cc1d4d646cf.png)

**Comment by LizDragoness** [comment]
The same is true if I start as the Zenox in tech three, no requirement for Crystal sensors, Enhanced Sensors exclusively.
![image](https://user-images.githubusercontent.com/123353916/215814450-a5fd206d-0395-4edb-9507-dd0cbf5d4498.png)
![image](https://user-images.githubusercontent.com/123353916/215814515-fb541897-068f-4623-95ea-d0f5f078bcda.png)

**Comment by lucky-wolf** [comment]
Ah!  Apologies - you're quite right!  When I moved the specialized line around - I failed to add those extra optional dependencies - as I have for BBs and BVs.  Will add!  Thanks!

**Comment by lucky-wolf** [comment]
Updated with a bug-fix just for you!
Thanks for persisting with this request.  Sorry I didn't understand you the first time.
https://github.com/lucky-wolf/DW2-XL/releases/tag/v1.9.2
