### ISSUE TITLE
Fusion Beam icons missing

### ISSUE THREAD

**Issue by szaki2** [lucky-wolf/DW2-XL#5]
Fusion Beam icons not show just a ? there. 
I am not sure the mod or the game :)
![kép](https://user-images.githubusercontent.com/68543170/223657643-d8814505-816d-42c6-9265-a02625c5390a.png)

**Comment by lucky-wolf** [comment]
@szaki2 how did you get a base that had those components?  They should be inaccessible.  I guess this is a pirate base?  base game might have a bug here - but thanks for pointing it out.  I have removed all fusion weapons, per vanilla change, in next build.

**Comment by szaki2** [comment]
Hello

Yes that was on a Pirate base.
________________________________
Feladó: Steve Wolf ***@***.***>
Küldve: 2023. március 10., péntek 15:28
Címzett: lucky-wolf/DW2-XL
Másolat: szaki2; Mention
Tárgy: Re: [lucky-wolf/DW2-XL] Fusion Beam icons missing (Issue #5)


@szaki2<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fszaki2&data=05%7C01%7C%7Cdbb4b5566338479bc8d308db2173af35%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638140553004018921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lPH22YMh7VMFB5KT4i0VC%2Fojre4SQQwWYAfChufiYBc%3D&reserved=0> how did you get a base that had those components? They should be inaccessible. I guess this is a pirate base? base game might have a bug here - but thanks for pointing it out. I have removed all fusion weapons, per vanilla change, in next build.

**Comment by lucky-wolf** [comment]
These were removed from the base game.  pirates should not be spawning with them now.  This tech is part of a DLC (eventually) - hence, no icons.
